math <- read.table("math.csv",sep=",",header=FALSE)  
sc <- ma
sc <- math[[2]]
plot(sc)
ssc <- sort(sc)
plot(ssc)
mean(sc)
median(sc)
min(sc)
max(sc)
var(sc)
sd(sc)
sprt(sc)
sqrt(sc)
table(sc)
barplot(table(sc))
hist(sc,breaks=seq(0,100,10))
hist(sc,br=6,col="#ab0000", border="red")
hist(sc,breaks=c(0,35,50,65,80,100),col="#ab0000",border="red")
